### ISSUE TITLE
Clockfile naming convention

### ISSUE THREAD

**Issue by bwgref** [NuSTAR/nustar-clock-utils#11]
Assuming #10 is fixed, then we need to do CCNM0001= 'CLOCK' to make sure that byproducts and nupipeline find the clockfile (currently it is CCNM0001= 'FINECLOCK').

Alternative is that we'll need a NuSTARDAS patch so that nupipeline and nuproducts know to look for the FINECLOCK file in the CALDB.

**Comment by matteobachetti** [comment]
@bwgref is this solved?

**Comment by bwgref** [comment]
@matteobachetti Yes, sorry for not closing it sooner!
