### ISSUE TITLE
Turn on/off the rolling trend plots

### ISSUE THREAD

**Issue by bwgref** [NuSTAR/nustar-clock-utils#14]
...is there a way in holoviz to have the trend plot get turned on/off in the legend like we have the ground stations?

From looking at the code I couldn't figure how that actually works (I think the residuals are all a part of the same data frame for all of the ground stations and there's some magic happening behind the scenes to make that work). But I don't know hv in any kind of detail to figure out how to add that.

**Comment by matteobachetti** [comment]
It should be sufficient to add it to the legend. I'll take a look tomorrow, if you can't work on it before
